apiVersion: v1
kind: Secret
metadata:
  name: kidsfun-django-secret
  namespace: default
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-(y@^qkirxh^6wd9#913ts$a!3j@!gfrnsv-lj@_%$+%$iml*k2"
  DB_PASSWORD: "Karin2100"
  EMAIL_HOST_PASSWORD: "your-email-password" # Cambiar por la real de Gmail
  # Aquí se puede agregar el contenido del JSON de Firebase si se prefiere como string
  # o manejarlo como un archivo montado desde otro Secret.
