# Generated by Django 4.2.11 on 2024-05-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0005_product_dimensions_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='important',
            new_name='publicated',
        ),
    ]
