# Generated by Django 4.2.13 on 2024-07-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0013_event_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('relative_name', models.CharField(max_length=100)),
                ('relative_age', models.IntegerField()),
            ],
        ),
    ]
