# Generated by Django 4.2.11 on 2025-08-13 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0022_chatroom_chatmessage_chatadministrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 't_app_contact_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
    ]
