# Generated by Django 4.2.11 on 2026-01-25 03:43

from django.db import migrations, models
import django.utils.timezone
import t_app_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0027_commentreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default_event.jpg', null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path_1),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path_2),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path_3),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path_4),
        ),
        migrations.AlterField(
            model_name='product',
            name='img5',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path_5),
        ),
    ]
