# Generated by Django 4.2.11 on 2026-03-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiver_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Documento de Exención de Responsabilidad (Waiver)', max_length=200)),
                ('content', models.TextField(help_text='Texto legal completo del waiver')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Waiver',
                'verbose_name_plural': 'Documento Waiver',
            },
        ),
    ]
