# Generated by Django 4.2.13 on 2024-07-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_waiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='waiverdata',
            table='api_waiver_waiverdata',
        ),
    ]
