# Generated by Django 4.2.13 on 2024-07-13 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_waiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api_waiver.userdata'),
            preserve_default=False,
        ),
    ]
