# Generated by Django 4.2.16 on 2024-09-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_waiver', '0002_alter_waiverdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverQR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_value', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='waiverdata',
            name='timestamp',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waiverdata',
            name='user_email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
