# Generated by Django 4.2.13 on 2024-06-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_app_commentary',
            },
        ),
    ]
