# Generated by Django 4.2.13 on 2025-07-30 15:11

from django.db import migrations, models
import django.db.models.deletion
import waiver_v2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverQRV2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code', models.CharField(default=waiver_v2.models.generate_unique_qr, max_length=8, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10)),
            ],
            options={
                'db_table': 'waiver_v2_waiverqr',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaiverDataV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_name', models.CharField(max_length=100)),
                ('relative_age', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('waiver_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='waiver_v2.waiverqrv2')),
            ],
            options={
                'db_table': 'waiver_v2_waiverdata',
                'ordering': ['-timestamp'],
            },
        ),
    ]
