# Generated by Django 4.2.11 on 2026-03-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiver_v2', '0002_waiverdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverScanV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_by', models.CharField(help_text='Email del colaborador que escaneó', max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('waiver_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='waiver_v2.waiverqrv2')),
            ],
            options={
                'db_table': 'waiver_v2_waiverscan',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
