# Generated by Django 4.2.11 on 2024-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='default_product_image.jpg', upload_to='product_images/'),
        ),
    ]
