# Generated by Django 4.2.11 on 2024-04-20 23:54

from django.db import migrations, models
import t_app_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='img5',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('option1', 'Bounce House'), ('option2', 'Mechanical Games'), ('option3', 'Furniture')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='default_product_image.jpg', upload_to=t_app_product.models.image_path),
        ),
    ]
