# Generated by Django 4.2.11 on 2024-05-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0006_rename_important_product_puclicated'),
    ]

    operations = [
    ]
