# Generated by Django 4.2.13 on 2024-07-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0009_alter_product_category_alter_product_youtube_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
    ]
