# Generated by Django 4.2.13 on 2024-07-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0010_remove_event_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_quantity',
        ),
    ]
