# Generated by Django 4.2.13 on 2024-07-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0011_remove_event_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
