# Generated by Django 4.2.13 on 2024-07-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0012_alter_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='partners',
            field=models.CharField(choices=[('partner1', 'Kidsfun'), ('partner2', 'Tecun Productions'), ('partner3', 'Otros')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
