# Generated by Django 4.2.13 on 2024-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0014_waiverdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiverdata',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='waiverdata',
            table='t_app_product_waiverdata',
        ),
    ]
