# Generated by Django 4.2.16 on 2024-09-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0015_alter_waiverdata_user_id_alter_waiverdata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='circuits_needed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='space_needed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('option1', 'Bounce House'), ('option2', 'Electric Games'), ('option3', 'Furniture'), ('option 4', 'Concession Machines'), ('option5', 'Competitive Games'), ('option6', 'Equipment Rental'), ('option7', 'Water Fun for Rent')], max_length=50),
        ),
    ]
