# Generated by Django 4.2.16 on 2024-09-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0016_product_circuits_needed_product_space_needed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='circuits_needed',
            new_name='circuits',
        ),
    ]
