# Generated by Django 4.2.16 on 2024-09-13 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0017_rename_circuits_needed_product_circuits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='space_needed',
            new_name='space',
        ),
    ]
