# Generated by Django 5.1.1 on 2024-09-26 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0018_rename_space_needed_product_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('option1', 'Bounce House'), ('option2', 'Electric Games'), ('option3', 'Furniture'), ('option4', 'Concession Machines'), ('option5', 'Competitive Games'), ('option6', 'Equipment Rental'), ('option7', 'Water Fun for Rent')], max_length=50),
        ),
        migrations.CreateModel(
            name='WaiverValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
