# Generated by Django 4.2.13 on 2025-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0020_alter_waivervalidator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverDataDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('relative_name', models.CharField(max_length=100)),
                ('relative_age', models.IntegerField()),
                ('timestamp', models.CharField(max_length=30)),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_waiver_waiverdata',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='waivervalidator',
            table='t_app_product_waivervalidator',
        ),
    ]
