# Generated by Django 4.2.11 on 2025-08-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0025_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlike', to='t_app_product.product'),
        ),
    ]
