# Generated by Django 4.2.11 on 2025-08-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0024_productlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='t_app_product.product')),
            ],
            options={
                'db_table': 't_app_product_comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
