# Generated by Django 4.2.11 on 2025-08-29 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_app_product', '0026_add_related_name_to_productlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='t_app_product.productcomment')),
            ],
            options={
                'db_table': 't_app_product_comment_reply',
                'ordering': ['created_at'],
            },
        ),
    ]
